
import { Octokit } from "@octokit/rest";
import { IntegrationSeeder, SeederContext, SeedResult } from "../types";

export class GitHubSeeder implements IntegrationSeeder {
    async seed(context: SeederContext): Promise<SeedResult> {
        const octokit = new Octokit({ auth: context.accessToken });
        const timestamp = Date.now();
        const repoName = `assemblr-e2e-${timestamp}`;
        const createdResources: Record<string, any[]> = { repos: [], issues: [], prs: [] };

        try {
            console.log(`[GitHubSeeder] Creating repo: ${repoName}`);
            // 1. Create Repo
            const { data: repo } = await octokit.repos.createForAuthenticatedUser({
                name: repoName,
                description: "Automated Test Repo for Assemblr E2E",
                private: true
            });
            createdResources.repos.push(repo.name);

            const owner = repo.owner.login;

            // 2. Create Issues
            console.log(`[GitHubSeeder] Creating issues...`);
            for (let i = 1; i <= 5; i++) {
                const { data: issue } = await octokit.issues.create({
                    owner,
                    repo: repoName,
                    title: `Test Issue ${i}`,
                    body: `This is automated issue #${i} generated by Assemblr.`
                });
                createdResources.issues.push(issue.number);
            }

            // 3. Create Content (for PR)
            console.log(`[GitHubSeeder] Creating file...`);
            await octokit.repos.createOrUpdateFileContents({
                owner,
                repo: repoName,
                path: "README.md",
                message: "Initial commit",
                content: Buffer.from("Assemblr E2E Test Repo").toString("base64")
            });

            // 4. Create Branch
            const { data: ref } = await octokit.git.getRef({ owner, repo: repoName, ref: "heads/main" });
            const sha = ref.object.sha;

            const branchName = "feature/test-branch";
            await octokit.git.createRef({
                owner,
                repo: repoName,
                ref: `refs/heads/${branchName}`,
                sha
            });

            // 5. Update File in Branch
            await octokit.repos.createOrUpdateFileContents({
                owner,
                repo: repoName,
                path: "README.md",
                message: "Update README",
                content: Buffer.from("Assemblr E2E Test Repo - Updated").toString("base64"),
                branch: branchName,
                sha: (await octokit.repos.getContent({ owner, repo: repoName, path: "README.md", ref: branchName }) as any).data.sha
            });

            // 6. Create PR
            console.log(`[GitHubSeeder] Creating PR...`);
            const { data: pr } = await octokit.pulls.create({
                owner,
                repo: repoName,
                title: "Test Pull Request",
                head: branchName,
                base: "main",
                body: "Automated PR"
            });
            createdResources.prs.push(pr.number);

            return { success: true, createdResources };

        } catch (e: any) {
            console.error(`[GitHubSeeder] Failed:`, e);
            // Attempt cleanup if partial failure? 
            return { success: false, createdResources, error: e.message };
        }
    }

    async cleanup(context: SeederContext, result: SeedResult): Promise<void> {
        const octokit = new Octokit({ auth: context.accessToken });
        const { data: user } = await octokit.users.getAuthenticated();

        for (const repoName of result.createdResources.repos || []) {
            console.log(`[GitHubSeeder] Deleting repo: ${repoName}`);
            await octokit.repos.delete({
                owner: user.login,
                repo: repoName
            });
        }
    }
}
