import Link from "next/link";
import { Footer } from "@/components/landing/footer";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-background text-foreground flex flex-col">
            {/* Simple Header */}
            <header className="border-b border-border/40 bg-background/80 backdrop-blur-xl sticky top-0 z-50">
                <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-6">
                    <Link href="/" className="font-semibold tracking-tight text-lg">
                        Assemblr
                    </Link>
                    <div className="flex gap-4 text-sm font-medium">
                        <Link href="/" className="text-muted-foreground hover:text-foreground transition-colors">Return Home</Link>
                    </div>
                </div>
            </header>

            <main className="flex-1 px-6 py-16 md:py-24">
                <article className="mx-auto max-w-3xl prose prose-slate dark:prose-invert prose-headings:scroll-mt-20">
                    <h1 className="text-4xl font-bold tracking-tight mb-4">Terms of Service</h1>
                    <p className="lead text-xl text-muted-foreground mb-12">
                        Last Updated: February 5, 2026
                    </p>

                    <p>
                        Please read these Terms of Service ("Terms") carefully before using the Assemblr website and services (the "Service") operated by Assemblr Inc. ("Assemblr", "we", "us", or "our").
                        By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.
                    </p>

                    <h2>1. Use of Service</h2>
                    <h3>1.1 Eligibility</h3>
                    <p>
                        You must be at least 18 years old to use the Service. By agreeing to these Terms, you represent and warrant that you are at least 18 years of age.
                    </p>

                    <h3>1.2 Account Registration</h3>
                    <p>
                        You may be required to register for an account to access certain features. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete. You are responsible for safeguarding your password and for all activities that occur under your account.
                    </p>

                    <h3>1.3 Acceptable Use</h3>
                    <p>You agree not to use the Service to:</p>
                    <ul>
                        <li>Generate content that is illegal, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable.</li>
                        <li>Reverse engineer, decompile, or disassemble any aspect of the Service.</li>
                        <li>Use the Service to build a competitive product or service.</li>
                        <li>Interfere with or disrupt the integrity or performance of the Service.</li>
                    </ul>

                    <h2>2. AI-Generated Content</h2>
                    <h3>2.1 Output Ownership</h3>
                    <p>
                        Subject to your compliance with these Terms, you own all right, title, and interest in and to the content generated by the Service specifically for you ("Output"), including any tools, workflows, or code.
                    </p>

                    <h3>2.2 Accuracy and Reliability</h3>
                    <p>
                        The Service utilizes artificial intelligence and machine learning technologies that may produce inaccurate or offensive Output. You acknowledge that:
                    </p>
                    <ul>
                        <li>Output may not be unique across users.</li>
                        <li>You are responsible for evaluating the accuracy and suitability of Output for your use case.</li>
                        <li>Automated workflows generated by the Service should be tested before deployment in critical environments.</li>
                    </ul>

                    <h2>3. Third-Party Integrations</h2>
                    <p>
                        The Service allows you to integrate with third-party software (e.g., GitHub, Slack). Use of such integrations is governed by the terms and policies of those third parties. We are not responsible for the operation or security of any third-party services.
                    </p>

                    <h2>4. Intellectual Property</h2>
                    <p>
                        The Service and its original content (excluding User Input and Output), features, and functionality are and will remain the exclusive property of Assemblr Inc. and its licensors.
                    </p>

                    <h2>5. Subscription and Billing</h2>
                    <p>
                        Certain aspects of the Service may be provided for a fee. You agree to pay all fees associated with your use of the Service. We reserve the right to change our pricing upon notice to you.
                    </p>

                    <h2>6. Termination</h2>
                    <p>
                        We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease.
                    </p>

                    <h2>7. Limitation of Liability</h2>
                    <p>
                        In no event shall Assemblr Inc., its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage.
                    </p>

                    <h2>8. Disclaimer</h2>
                    <p>
                        Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied.
                    </p>

                    <h2>9. Governing Law</h2>
                    <p>
                        These Terms shall be governed and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions.
                    </p>

                    <h2>10. Changes to Terms</h2>
                    <p>
                        We reserve the right, at our sole discretion, to modify or replace these Terms at any time. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
                    </p>

                    <h2>11. Contact Us</h2>
                    <p>
                        If you have any questions about these Terms, please contact us at: <a href="mailto:legal@assemblr.ai">legal@assemblr.ai</a>
                    </p>
                </article>
            </main>

            <Footer />
        </div>
    );
}
