import type { UseCaseDefinition } from "../categories";
import { buildSpec } from "../build-spec";
import { makeGithubPREntity, makeGithubIssueEntity, makeGithubRepoEntity, makeGithubCommitEntity, makeLinearIssueEntity, makeLinearProjectEntity, makeLinearCycleEntity, makeGitlabMREntity, makeGitlabPipelineEntity, makeJiraIssueEntity } from "../entity-builders";
import { makeGithubPRListAction, makeGithubIssueListAction, makeGithubRepoListAction, makeGithubCommitsListAction, makeGithubCommitStatusAction, makeGithubPRReviewsAction, makeLinearIssuesListAction, makeLinearProjectsListAction, makeLinearCyclesListAction, makeGitlabMRListAction, makeGitlabPipelinesListAction, makeJiraIssuesSearchAction } from "../action-builders";

export const engineeringUseCases: UseCaseDefinition[] = [
  // 1. PR Review Tracker
  {
    id: "eng-pr-review-tracker",
    name: "PR Review Tracker",
    description: "Monitor all open pull requests, reviewer assignments, and review turnaround times.",
    category: "Engineering",
    integrations: ["github"],
    trigger: "Prompt-based",
    output: "Table",
    prompt: "Show me all open pull requests with review status and how long they've been waiting.",
    spec: buildSpec({
      id: "eng-pr-review-tracker",
      name: "PR Review Tracker",
      description: "Monitor open pull requests and review cycle times.",
      purpose: "Identify PRs awaiting review and track reviewer responsiveness.",
      integrations: ["github"],
      entities: [makeGithubPREntity()],
      actions: [makeGithubPRListAction(), makeGithubPRReviewsAction()],
      views: [
        {
          id: "pr-table",
          name: "Open Pull Requests",
          type: "table",
          source: { entity: "PullRequest", statePath: "github.pr" },
          fields: ["title", "number", "state", "author", "assignees", "created_at", "updated_at", "draft", "review_comments", "changed_files", "html_url"],
          actions: ["github.pr.list"],
        },
        {
          id: "pr-dashboard",
          name: "Review Overview",
          type: "dashboard",
          source: { entity: "PullRequest", statePath: "github.pr" },
          fields: ["state", "author", "created_at", "review_comments"],
          actions: [],
        },
      ],
      query_plans: [{ integrationId: "github", actionId: "github.pr.list", query: { q: "is:pr is:open", sort: "updated", order: "desc", per_page: 50 }, fields: ["title", "number", "state", "author", "created_at"], max_results: 50 }],
      answer_contract: { entity_type: "PullRequest", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array", result_shape: { kind: "list", fields: ["title", "number", "state", "author", "created_at"], order_by: "updated_at", order_direction: "desc" } },
    }),
  },

  // 2. CI/CD Pipeline Monitor
  {
    id: "eng-ci-pipeline-monitor",
    name: "CI/CD Pipeline Monitor",
    description: "Track CI/CD pipeline health, build statuses, and deployment success rates across GitLab and GitHub.",
    category: "Engineering",
    integrations: ["gitlab", "github"],
    trigger: "Time-based",
    output: "Table",
    prompt: "Show me all recent CI/CD pipelines with their status and duration.",
    spec: buildSpec({
      id: "eng-ci-pipeline-monitor",
      name: "CI/CD Pipeline Monitor",
      description: "Track CI/CD pipeline health and build statuses.",
      purpose: "Monitor pipeline reliability and identify failing builds.",
      integrations: ["gitlab", "github"],
      entities: [makeGitlabPipelineEntity(), makeGithubPREntity()],
      actions: [makeGitlabPipelinesListAction(), makeGithubCommitStatusAction()],
      views: [
        {
          id: "pipelines-table",
          name: "Pipelines",
          type: "table",
          source: { entity: "Pipeline", statePath: "gitlab.pipelines" },
          fields: ["id", "status", "ref", "sha", "created_at", "duration", "web_url"],
          actions: ["gitlab.pipelines.list"],
        },
        {
          id: "pipeline-dashboard",
          name: "Pipeline Health",
          type: "dashboard",
          source: { entity: "Pipeline", statePath: "gitlab.pipelines" },
          fields: ["status", "duration", "ref"],
          actions: [],
        },
      ],
      query_plans: [{ integrationId: "gitlab", actionId: "gitlab.pipelines.list", query: {}, fields: ["id", "status", "ref", "sha", "duration"], max_results: 50 }],
      answer_contract: { entity_type: "Pipeline", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },

  // 3. Sprint Velocity Dashboard
  {
    id: "eng-sprint-velocity",
    name: "Sprint Velocity Dashboard",
    description: "Track sprint progress, velocity trends, and cycle completion rates from Linear.",
    category: "Engineering",
    integrations: ["linear"],
    trigger: "Prompt-based",
    output: "Summary",
    prompt: "Show me the current sprint velocity and progress for all teams.",
    spec: buildSpec({
      id: "eng-sprint-velocity",
      name: "Sprint Velocity Dashboard",
      description: "Sprint progress and velocity tracking.",
      purpose: "Measure team delivery speed and sprint health.",
      integrations: ["linear"],
      entities: [makeLinearIssueEntity(), makeLinearCycleEntity()],
      actions: [makeLinearIssuesListAction(), makeLinearCyclesListAction()],
      views: [
        {
          id: "sprint-dashboard",
          name: "Sprint Overview",
          type: "dashboard",
          source: { entity: "LinearIssue", statePath: "linear.issues" },
          fields: ["state", "priority", "assignee", "estimate", "completedAt"],
          actions: [],
        },
        {
          id: "issues-table",
          name: "Sprint Issues",
          type: "table",
          source: { entity: "LinearIssue", statePath: "linear.issues" },
          fields: ["title", "identifier", "state", "priority", "assignee", "team", "estimate", "dueDate", "completedAt", "url"],
          actions: ["linear.issues.list"],
        },
      ],
      query_plans: [{ integrationId: "linear", actionId: "linear.issues.list", query: {}, fields: ["title", "identifier", "state", "priority", "assignee", "estimate"], max_results: 100 }],
      answer_contract: { entity_type: "LinearIssue", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },

  // 4. Issue Triage Board
  {
    id: "eng-open-issue-triage",
    name: "Issue Triage Board",
    description: "Unified view of open issues from GitHub and Linear for triage and prioritization.",
    category: "Engineering",
    integrations: ["github", "linear"],
    trigger: "Prompt-based",
    output: "Table",
    prompt: "Show me all open issues that need triage from GitHub and Linear.",
    spec: buildSpec({
      id: "eng-open-issue-triage",
      name: "Issue Triage Board",
      description: "Unified issue triage across GitHub and Linear.",
      purpose: "Prioritize and triage incoming issues from all sources.",
      integrations: ["github", "linear"],
      entities: [makeGithubIssueEntity(), makeLinearIssueEntity()],
      actions: [makeGithubIssueListAction(), makeLinearIssuesListAction()],
      views: [
        {
          id: "issues-kanban",
          name: "Issue Triage Board",
          type: "kanban",
          source: { entity: "Issue", statePath: "github.issue" },
          fields: ["title", "number", "state", "labels", "assignee", "created_at", "comments", "html_url"],
          actions: ["github.issue.list"],
        },
        {
          id: "issues-table",
          name: "All Issues",
          type: "table",
          source: { entity: "Issue", statePath: "github.issue" },
          fields: ["title", "number", "state", "labels", "assignee", "created_at", "updated_at", "comments", "html_url"],
          actions: ["github.issue.list"],
        },
      ],
      query_plans: [
        { integrationId: "github", actionId: "github.issue.list", query: { q: "is:issue is:open", sort: "created", order: "desc", per_page: 50 }, fields: ["title", "number", "state", "labels", "assignee"], max_results: 50 },
        { integrationId: "linear", actionId: "linear.issues.list", query: {}, fields: ["title", "identifier", "state", "priority", "assignee"], max_results: 50 },
      ],
      answer_contract: { entity_type: "Issue", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },

  // 5. Repository Health Monitor
  {
    id: "eng-repo-health",
    name: "Repository Health Monitor",
    description: "Monitor repository activity, open issues, stars, and contributor engagement.",
    category: "Engineering",
    integrations: ["github"],
    trigger: "Prompt-based",
    output: "Table",
    prompt: "Show me the health status of all our GitHub repositories.",
    spec: buildSpec({
      id: "eng-repo-health",
      name: "Repository Health Monitor",
      description: "Track repository metrics and health indicators.",
      purpose: "Identify neglected repositories and track activity trends.",
      integrations: ["github"],
      entities: [makeGithubRepoEntity()],
      actions: [makeGithubRepoListAction()],
      views: [
        {
          id: "repos-table",
          name: "Repositories",
          type: "table",
          source: { entity: "Repository", statePath: "github.repos" },
          fields: ["name", "full_name", "description", "language", "stargazers_count", "forks_count", "open_issues_count", "updated_at", "pushed_at", "visibility", "html_url"],
          actions: ["github.repos.list"],
        },
        {
          id: "repos-dashboard",
          name: "Health Overview",
          type: "dashboard",
          source: { entity: "Repository", statePath: "github.repos" },
          fields: ["language", "stargazers_count", "open_issues_count", "visibility"],
          actions: [],
        },
      ],
      query_plans: [{ integrationId: "github", actionId: "github.repos.list", query: { type: "all", sort: "updated" }, fields: ["name", "language", "stargazers_count", "open_issues_count"], max_results: 50 }],
      answer_contract: { entity_type: "Repository", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },

  // 6. Tech Debt Tracker
  {
    id: "eng-tech-debt-tracker",
    name: "Tech Debt Tracker",
    description: "Surface stale issues, long-lived bugs, and tech debt items from GitHub and Linear.",
    category: "Engineering",
    integrations: ["github", "linear"],
    trigger: "Prompt-based",
    output: "Table",
    prompt: "Show me all tech debt issues and long-standing bugs from GitHub and Linear.",
    spec: buildSpec({
      id: "eng-tech-debt-tracker",
      name: "Tech Debt Tracker",
      description: "Track and prioritize technical debt.",
      purpose: "Surface stale issues and prioritize maintenance work.",
      integrations: ["github", "linear"],
      entities: [makeGithubIssueEntity(), makeLinearIssueEntity()],
      actions: [
        { ...makeGithubIssueListAction(), inputSchema: { q: "is:issue is:open label:bug,tech-debt,maintenance", sort: "created", order: "asc", per_page: 50 } },
        makeLinearIssuesListAction(),
      ],
      views: [
        {
          id: "debt-table",
          name: "Tech Debt Issues",
          type: "table",
          source: { entity: "Issue", statePath: "github.issue" },
          fields: ["title", "number", "state", "labels", "assignee", "created_at", "updated_at", "comments", "html_url"],
          actions: ["github.issue.list"],
        },
      ],
      query_plans: [{ integrationId: "github", actionId: "github.issue.list", query: { q: "is:issue is:open label:bug,tech-debt", sort: "created", order: "asc", per_page: 50 }, fields: ["title", "number", "labels", "created_at"], max_results: 50 }],
      answer_contract: { entity_type: "Issue", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },

  // 7. Release Readiness Checklist
  {
    id: "eng-release-checklist",
    name: "Release Readiness Checklist",
    description: "Check open PRs, unresolved issues, and blocking items before release.",
    category: "Engineering",
    integrations: ["github", "linear"],
    trigger: "Prompt-based",
    output: "Alert",
    prompt: "Are we ready to release? Check all open PRs and blocking issues.",
    spec: buildSpec({
      id: "eng-release-checklist",
      name: "Release Readiness Checklist",
      description: "Aggregated release risk assessment.",
      purpose: "Determine if current state meets release criteria.",
      integrations: ["github", "linear"],
      entities: [makeGithubPREntity(), makeLinearIssueEntity()],
      actions: [makeGithubPRListAction(), makeLinearIssuesListAction()],
      views: [
        {
          id: "release-dashboard",
          name: "Release Readiness",
          type: "dashboard",
          source: { entity: "PullRequest", statePath: "github.pr" },
          fields: ["state", "draft", "review_comments", "changed_files"],
          actions: [],
        },
        {
          id: "blocking-table",
          name: "Blocking Items",
          type: "table",
          source: { entity: "PullRequest", statePath: "github.pr" },
          fields: ["title", "number", "state", "author", "draft", "review_comments", "changed_files", "html_url"],
          actions: ["github.pr.list"],
        },
      ],
      query_plans: [
        { integrationId: "github", actionId: "github.pr.list", query: { q: "is:pr is:open", sort: "updated", order: "desc", per_page: 50 }, fields: ["title", "state", "draft", "review_comments"], max_results: 50 },
        { integrationId: "linear", actionId: "linear.issues.list", query: {}, fields: ["title", "state", "priority"], max_results: 50 },
      ],
      answer_contract: { entity_type: "PullRequest", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },

  // 8. Contributor Activity Map
  {
    id: "eng-contributor-map",
    name: "Contributor Activity Map",
    description: "Visualize contributor activity, commit frequency, and repository ownership.",
    category: "Engineering",
    integrations: ["github"],
    trigger: "Prompt-based",
    output: "Table",
    prompt: "Show me contributor activity and commit patterns across all repositories.",
    spec: buildSpec({
      id: "eng-contributor-map",
      name: "Contributor Activity Map",
      description: "Visualize contributor patterns and ownership.",
      purpose: "Understand knowledge distribution and reduce bus factor risk.",
      integrations: ["github"],
      entities: [makeGithubRepoEntity(), makeGithubCommitEntity()],
      actions: [makeGithubRepoListAction(), makeGithubCommitsListAction()],
      views: [
        {
          id: "repos-table",
          name: "Repository Activity",
          type: "table",
          source: { entity: "Repository", statePath: "github.repos" },
          fields: ["name", "full_name", "language", "stargazers_count", "open_issues_count", "pushed_at", "html_url"],
          actions: ["github.repos.list"],
        },
      ],
      query_plans: [{ integrationId: "github", actionId: "github.repos.list", query: { type: "all", sort: "pushed" }, fields: ["name", "language", "pushed_at"], max_results: 50 }],
      answer_contract: { entity_type: "Repository", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },

  // 9. Deployment Tracker
  {
    id: "eng-deploy-tracker",
    name: "Deployment Tracker",
    description: "Track deployments and pipeline runs across GitLab and GitHub.",
    category: "Engineering",
    integrations: ["gitlab", "github"],
    trigger: "Prompt-based",
    output: "Table",
    prompt: "Show me all recent deployments and their success rates.",
    spec: buildSpec({
      id: "eng-deploy-tracker",
      name: "Deployment Tracker",
      description: "Monitor deployment frequency and success rates.",
      purpose: "Track deployment cadence and reliability.",
      integrations: ["gitlab", "github"],
      entities: [makeGitlabPipelineEntity(), makeGitlabMREntity()],
      actions: [makeGitlabPipelinesListAction(), makeGitlabMRListAction()],
      views: [
        {
          id: "deploys-table",
          name: "Deployments",
          type: "table",
          source: { entity: "Pipeline", statePath: "gitlab.pipelines" },
          fields: ["id", "status", "ref", "sha", "created_at", "updated_at", "duration", "web_url"],
          actions: ["gitlab.pipelines.list"],
        },
        {
          id: "deploys-timeline",
          name: "Deploy Timeline",
          type: "timeline",
          source: { entity: "Pipeline", statePath: "gitlab.pipelines" },
          fields: ["status", "ref", "created_at", "duration"],
          actions: [],
        },
      ],
      query_plans: [{ integrationId: "gitlab", actionId: "gitlab.pipelines.list", query: {}, fields: ["id", "status", "ref", "duration"], max_results: 50 }],
      answer_contract: { entity_type: "Pipeline", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },

  // 10. Bug Triage Queue
  {
    id: "eng-bug-triage-queue",
    name: "Bug Triage Queue",
    description: "Unified bug queue from GitHub and Jira for triage and assignment.",
    category: "Engineering",
    integrations: ["github", "jira"],
    trigger: "Prompt-based",
    output: "Table",
    prompt: "Show me all open bugs from GitHub and Jira that need triage.",
    spec: buildSpec({
      id: "eng-bug-triage-queue",
      name: "Bug Triage Queue",
      description: "Unified bug queue for triage.",
      purpose: "Quickly triage and assign incoming bug reports.",
      integrations: ["github", "jira"],
      entities: [makeGithubIssueEntity(), makeJiraIssueEntity()],
      actions: [
        { ...makeGithubIssueListAction(), inputSchema: { q: "is:issue is:open label:bug", sort: "created", order: "desc", per_page: 50 } },
        makeJiraIssuesSearchAction(),
      ],
      views: [
        {
          id: "bugs-kanban",
          name: "Bug Triage Board",
          type: "kanban",
          source: { entity: "Issue", statePath: "github.issue" },
          fields: ["title", "number", "state", "labels", "assignee", "created_at", "html_url"],
          actions: ["github.issue.list"],
        },
        {
          id: "bugs-table",
          name: "All Bugs",
          type: "table",
          source: { entity: "Issue", statePath: "github.issue" },
          fields: ["title", "number", "state", "labels", "assignee", "created_at", "updated_at", "comments", "html_url"],
          actions: ["github.issue.list"],
        },
      ],
      query_plans: [{ integrationId: "github", actionId: "github.issue.list", query: { q: "is:issue is:open label:bug", sort: "created", order: "desc", per_page: 50 }, fields: ["title", "number", "state", "labels"], max_results: 50 }],
      answer_contract: { entity_type: "Issue", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },
];
