import type { UseCaseDefinition } from "../categories";
import { buildSpec } from "../build-spec";
import { makeIntercomConversationEntity, makeIntercomCompanyEntity, makeHubspotCompanyEntity, makeHubspotDealEntity, makeGithubIssueEntity, makeLinearIssueEntity, makeOutlookEmailEntity, makeOutlookEventEntity, makeTeamsMessageEntity, makeAsanaProjectEntity, makeAsanaTaskEntity, makeTrelloBoardEntity, makeTrelloCardEntity, makeAirtableRecordEntity, makeAirtableBaseEntity, makeNotionPageEntity, makeZoomMeetingEntity, makeGithubPREntity, makeSlackChannelEntity, makeZendeskTicketEntity } from "../entity-builders";
import { makeIntercomConversationsListAction, makeIntercomSearchConversationsAction, makeIntercomCompaniesListAction, makeHubspotCompaniesListAction, makeHubspotDealsListAction, makeGithubIssueListAction, makeGithubPRListAction, makeLinearIssuesListAction, makeOutlookMessagesListAction, makeOutlookEventsListAction, makeTeamsMessagesListAction, makeAsanaProjectsListAction, makeTrelloBoardsListAction, makeAirtableRecordsListAction, makeAirtableBasesListAction, makeNotionPagesSearchAction, makeZoomMeetingsListAction, makeSlackChannelsListAction, makeZendeskTicketsListAction } from "../action-builders";

export const operationsSupportUseCases: UseCaseDefinition[] = [
  {
    id: "ops-support-sla",
    name: "Support SLA Monitor",
    description: "Track open conversations and ticket SLA compliance across Intercom.",
    category: "Operations & Support",
    integrations: ["intercom"],
    trigger: "Time-based",
    output: "Table",
    prompt: "Show me all open Intercom conversations sorted by waiting time with SLA status.",
    spec: buildSpec({
      id: "ops-support-sla",
      name: "Support SLA Monitor",
      description: "Live SLA tracking for support conversations.",
      purpose: "Ensure support tickets are handled within SLA windows.",
      integrations: ["intercom"],
      entities: [makeIntercomConversationEntity()],
      actions: [makeIntercomConversationsListAction()],
      views: [
        { id: "sla-table", name: "Conversation Queue", type: "table", source: { entity: "Conversation", statePath: "intercom.conversations" }, fields: ["id", "state", "subject", "contact_name", "assignee", "priority", "created_at", "updated_at", "waiting_since", "open"], actions: ["intercom.conversations.list"] },
        { id: "sla-dashboard", name: "SLA Overview", type: "dashboard", source: { entity: "Conversation", statePath: "intercom.conversations" }, fields: ["state", "priority", "assignee", "waiting_since"], actions: [] },
      ],
      query_plans: [{ integrationId: "intercom", actionId: "intercom.conversations.list", query: { per_page: 50 }, fields: ["id", "state", "priority", "waiting_since"], max_results: 50 }],
      answer_contract: { entity_type: "Conversation", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },
  {
    id: "ops-ticket-queue",
    name: "Ticket Queue Manager",
    description: "Manage Intercom conversation queue with search and priority filtering.",
    category: "Operations & Support",
    integrations: ["intercom"],
    trigger: "Prompt-based",
    output: "Table",
    prompt: "Show me the ticket queue sorted by priority and waiting time.",
    spec: buildSpec({
      id: "ops-ticket-queue",
      name: "Ticket Queue Manager",
      description: "Priority-based ticket queue management.",
      purpose: "Efficiently triage and assign support conversations.",
      integrations: ["intercom"],
      entities: [makeIntercomConversationEntity()],
      actions: [makeIntercomConversationsListAction(), makeIntercomSearchConversationsAction()],
      views: [
        { id: "queue-kanban", name: "Ticket Board", type: "kanban", source: { entity: "Conversation", statePath: "intercom.conversations" }, fields: ["id", "state", "subject", "contact_name", "assignee", "priority", "waiting_since", "open"], actions: ["intercom.conversations.list"] },
        { id: "queue-table", name: "All Tickets", type: "table", source: { entity: "Conversation", statePath: "intercom.conversations" }, fields: ["id", "state", "subject", "contact_name", "assignee", "priority", "created_at", "updated_at", "waiting_since", "open", "read"], actions: ["intercom.conversations.list"] },
      ],
      query_plans: [{ integrationId: "intercom", actionId: "intercom.conversations.list", query: { per_page: 50 }, fields: ["id", "state", "subject", "priority"], max_results: 50 }],
      answer_contract: { entity_type: "Conversation", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },
  {
    id: "ops-customer-health",
    name: "Customer Health Score",
    description: "Combined customer health from Intercom support data and HubSpot company profiles.",
    category: "Operations & Support",
    integrations: ["intercom", "hubspot"],
    trigger: "Time-based",
    output: "Table",
    prompt: "Show me customer health scores combining support and CRM data.",
    spec: buildSpec({
      id: "ops-customer-health",
      name: "Customer Health Score",
      description: "Cross-platform customer health assessment.",
      purpose: "Identify at-risk customers using support and CRM signals.",
      integrations: ["intercom", "hubspot"],
      entities: [makeIntercomCompanyEntity(), makeHubspotCompanyEntity()],
      actions: [makeIntercomCompaniesListAction(), makeHubspotCompaniesListAction()],
      views: [
        { id: "health-table", name: "Customer Health", type: "table", source: { entity: "IntercomCompany", statePath: "intercom.companies" }, fields: ["name", "company_id", "plan", "monthly_spend", "user_count", "session_count", "created_at", "last_request_at", "industry"], actions: ["intercom.companies.list"] },
        { id: "health-dashboard", name: "Health Overview", type: "dashboard", source: { entity: "IntercomCompany", statePath: "intercom.companies" }, fields: ["plan", "monthly_spend", "user_count", "industry"], actions: [] },
      ],
      query_plans: [
        { integrationId: "intercom", actionId: "intercom.companies.list", query: {}, fields: ["name", "plan", "monthly_spend", "user_count"], max_results: 50 },
        { integrationId: "hubspot", actionId: "hubspot.companies.list", query: {}, fields: ["name", "industry", "annualrevenue"], max_results: 50 },
      ],
      answer_contract: { entity_type: "IntercomCompany", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },
  {
    id: "ops-incident-tracker",
    name: "Incident Response Tracker",
    description: "Track active incidents from GitHub issues and Linear for rapid response.",
    category: "Operations & Support",
    integrations: ["github", "linear"],
    trigger: "Event-based",
    output: "Alert",
    prompt: "Show me all active incidents across GitHub and Linear.",
    spec: buildSpec({
      id: "ops-incident-tracker",
      name: "Incident Response Tracker",
      description: "Active incident monitoring and tracking.",
      purpose: "Coordinate incident response across engineering platforms.",
      integrations: ["github", "linear"],
      entities: [makeGithubIssueEntity(), makeLinearIssueEntity()],
      actions: [{ ...makeGithubIssueListAction(), inputSchema: { q: "is:issue is:open label:incident,bug,critical", sort: "created", order: "desc", per_page: 50 } }, makeLinearIssuesListAction()],
      views: [
        { id: "incidents-table", name: "Active Incidents", type: "table", source: { entity: "Issue", statePath: "github.issue" }, fields: ["title", "number", "state", "labels", "assignee", "created_at", "updated_at", "comments", "html_url"], actions: ["github.issue.list"] },
        { id: "incidents-dashboard", name: "Incident Overview", type: "dashboard", source: { entity: "Issue", statePath: "github.issue" }, fields: ["state", "labels", "assignee", "created_at"], actions: [] },
      ],
      query_plans: [{ integrationId: "github", actionId: "github.issue.list", query: { q: "is:issue is:open label:incident,bug", sort: "created", order: "desc", per_page: 50 }, fields: ["title", "state", "labels", "created_at"], max_results: 50 }],
      answer_contract: { entity_type: "Issue", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },
  {
    id: "ops-communication-hub",
    name: "Communication Hub",
    description: "Unified view of Outlook emails and Microsoft Teams messages.",
    category: "Operations & Support",
    integrations: ["outlook", "microsoft_teams"],
    trigger: "Prompt-based",
    output: "Table",
    prompt: "Show me recent communications from Outlook and Teams.",
    spec: buildSpec({
      id: "ops-communication-hub",
      name: "Communication Hub",
      description: "Unified communication monitoring.",
      purpose: "Aggregate messages across email and team chat.",
      integrations: ["outlook", "microsoft_teams"],
      entities: [makeOutlookEmailEntity(), makeTeamsMessageEntity()],
      actions: [makeOutlookMessagesListAction(), makeTeamsMessagesListAction()],
      views: [
        { id: "comms-table", name: "All Messages", type: "table", source: { entity: "Email", statePath: "outlook.messages" }, fields: ["subject", "from", "toRecipients", "receivedDateTime", "isRead", "importance", "bodyPreview", "hasAttachments"], actions: ["outlook.messages.list"] },
      ],
      query_plans: [
        { integrationId: "outlook", actionId: "outlook.messages.list", query: {}, fields: ["subject", "from", "receivedDateTime", "isRead"], max_results: 50 },
        { integrationId: "microsoft_teams", actionId: "teams.messages.list", query: {}, fields: ["body", "from", "createdDateTime"], max_results: 50 },
      ],
      answer_contract: { entity_type: "Email", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },
  {
    id: "ops-project-status",
    name: "Cross-Team Project Status",
    description: "Unified project view from Asana and Trello for cross-team visibility.",
    category: "Operations & Support",
    integrations: ["asana", "trello"],
    trigger: "Prompt-based",
    output: "Table",
    prompt: "Show me project status across all teams from Asana and Trello.",
    spec: buildSpec({
      id: "ops-project-status",
      name: "Cross-Team Project Status",
      description: "Cross-platform project status tracking.",
      purpose: "Unified view of project health across teams.",
      integrations: ["asana", "trello"],
      entities: [makeAsanaProjectEntity(), makeTrelloBoardEntity()],
      actions: [makeAsanaProjectsListAction(), makeTrelloBoardsListAction()],
      views: [
        { id: "projects-table", name: "All Projects", type: "table", source: { entity: "AsanaProject", statePath: "asana.projects" }, fields: ["name", "owner", "due_date", "start_on", "status", "archived", "created_at", "modified_at"], actions: ["asana.projects.list"] },
        { id: "boards-kanban", name: "Board View", type: "kanban", source: { entity: "TrelloBoard", statePath: "trello.boards" }, fields: ["name", "desc", "url", "dateLastActivity", "closed"], actions: ["trello.boards.list"] },
      ],
      query_plans: [
        { integrationId: "asana", actionId: "asana.projects.list", query: {}, fields: ["name", "owner", "status", "due_date"], max_results: 50 },
        { integrationId: "trello", actionId: "trello.boards.list", query: { idMember: "me" }, fields: ["name", "url"], max_results: 20 },
      ],
      answer_contract: { entity_type: "AsanaProject", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },
  {
    id: "ops-vendor-tracker",
    name: "Vendor Management Tracker",
    description: "Track vendor relationships and contracts from Airtable and Notion.",
    category: "Operations & Support",
    integrations: ["airtable", "notion"],
    trigger: "Prompt-based",
    output: "Table",
    prompt: "Show me all vendor records and contract status.",
    spec: buildSpec({
      id: "ops-vendor-tracker",
      name: "Vendor Management Tracker",
      description: "Vendor and contract management.",
      purpose: "Centralize vendor information and track contract status.",
      integrations: ["airtable", "notion"],
      entities: [makeAirtableRecordEntity(), makeNotionPageEntity()],
      actions: [makeAirtableRecordsListAction(), makeNotionPagesSearchAction()],
      views: [
        { id: "vendors-table", name: "Vendors", type: "table", source: { entity: "AirtableRecord", statePath: "airtable.records" }, fields: ["id", "createdTime", "fields"], actions: ["airtable.records.list"] },
      ],
      query_plans: [{ integrationId: "airtable", actionId: "airtable.records.list", query: {}, fields: ["id", "createdTime", "fields"], max_results: 50 }],
      answer_contract: { entity_type: "AirtableRecord", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },
  {
    id: "ops-meeting-tracker",
    name: "Meeting & Action Items",
    description: "Track meetings from Zoom and Outlook with action item follow-ups.",
    category: "Operations & Support",
    integrations: ["zoom", "outlook"],
    trigger: "Prompt-based",
    output: "Table",
    prompt: "Show me all recent meetings with their action items and follow-ups.",
    spec: buildSpec({
      id: "ops-meeting-tracker",
      name: "Meeting & Action Items",
      description: "Meeting tracking with action items.",
      purpose: "Ensure meeting outcomes are tracked and followed up.",
      integrations: ["zoom", "outlook"],
      entities: [makeZoomMeetingEntity(), makeOutlookEventEntity()],
      actions: [makeZoomMeetingsListAction(), makeOutlookEventsListAction()],
      views: [
        { id: "meetings-table", name: "All Meetings", type: "table", source: { entity: "Meeting", statePath: "zoom.meetings" }, fields: ["topic", "start_time", "duration", "host_id", "join_url", "status", "agenda", "created_at"], actions: ["zoom.meetings.list"] },
        { id: "meetings-timeline", name: "Meeting Timeline", type: "timeline", source: { entity: "Meeting", statePath: "zoom.meetings" }, fields: ["topic", "start_time", "duration", "status"], actions: [] },
      ],
      query_plans: [
        { integrationId: "zoom", actionId: "zoom.meetings.list", query: { userId: "me" }, fields: ["topic", "start_time", "duration", "status"], max_results: 50 },
        { integrationId: "outlook", actionId: "outlook.events.list", query: {}, fields: ["subject", "start", "end", "organizer"], max_results: 50 },
      ],
      answer_contract: { entity_type: "Meeting", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },
  {
    id: "ops-data-warehouse",
    name: "Airtable Data Dashboard",
    description: "Browse and analyze data from Airtable bases and records.",
    category: "Operations & Support",
    integrations: ["airtable"],
    trigger: "Prompt-based",
    output: "Table",
    prompt: "Show me all Airtable bases and their records.",
    spec: buildSpec({
      id: "ops-data-warehouse",
      name: "Airtable Data Dashboard",
      description: "Airtable data exploration and analysis.",
      purpose: "Centralized view of operational data in Airtable.",
      integrations: ["airtable"],
      entities: [makeAirtableBaseEntity(), makeAirtableRecordEntity()],
      actions: [makeAirtableBasesListAction(), makeAirtableRecordsListAction()],
      views: [
        { id: "bases-table", name: "Bases", type: "table", source: { entity: "AirtableBase", statePath: "airtable.bases" }, fields: ["id", "name", "permissionLevel"], actions: ["airtable.bases.list"] },
        { id: "data-dashboard", name: "Data Overview", type: "dashboard", source: { entity: "AirtableBase", statePath: "airtable.bases" }, fields: ["name", "permissionLevel"], actions: [] },
      ],
      query_plans: [{ integrationId: "airtable", actionId: "airtable.bases.list", query: {}, fields: ["id", "name", "permissionLevel"], max_results: 50 }],
      answer_contract: { entity_type: "AirtableBase", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },
  {
    id: "ops-crm-support-bridge",
    name: "CRM-to-Support Bridge",
    description: "Connect HubSpot deals with Intercom conversations for unified customer context.",
    category: "Operations & Support",
    integrations: ["hubspot", "intercom"],
    trigger: "Prompt-based",
    output: "Table",
    prompt: "Show me deals alongside their associated support conversations.",
    spec: buildSpec({
      id: "ops-crm-support-bridge",
      name: "CRM-to-Support Bridge",
      description: "CRM and support data correlation.",
      purpose: "Bridge sales and support data for complete customer context.",
      integrations: ["hubspot", "intercom"],
      entities: [makeHubspotDealEntity(), makeIntercomConversationEntity()],
      actions: [makeHubspotDealsListAction(), makeIntercomConversationsListAction()],
      views: [
        { id: "bridge-table", name: "Deal-Support View", type: "table", source: { entity: "Deal", statePath: "hubspot.deals" }, fields: ["dealname", "dealstage", "amount", "closedate", "pipeline", "hubspot_owner_id", "createdate"], actions: ["hubspot.deals.list"] },
      ],
      query_plans: [
        { integrationId: "hubspot", actionId: "hubspot.deals.list", query: {}, fields: ["dealname", "dealstage", "amount"], max_results: 50 },
        { integrationId: "intercom", actionId: "intercom.conversations.list", query: {}, fields: ["state", "subject", "contact_name"], max_results: 50 },
      ],
      answer_contract: { entity_type: "Deal", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },
  {
    id: "ops-compliance-tracker",
    name: "Compliance Audit Tracker",
    description: "Track compliance-relevant changes in Notion documentation and GitHub PRs.",
    category: "Operations & Support",
    integrations: ["notion", "github"],
    trigger: "Time-based",
    output: "Table",
    prompt: "Show me all compliance-relevant changes and audit trail items.",
    spec: buildSpec({
      id: "ops-compliance-tracker",
      name: "Compliance Audit Tracker",
      description: "Compliance and audit trail monitoring.",
      purpose: "Maintain audit trail for compliance requirements.",
      integrations: ["notion", "github"],
      entities: [makeNotionPageEntity(), makeGithubPREntity()],
      actions: [makeNotionPagesSearchAction(), makeGithubPRListAction()],
      views: [
        { id: "audit-table", name: "Audit Trail", type: "table", source: { entity: "NotionPage", statePath: "notion.pages" }, fields: ["title", "url", "last_edited_time", "created_time", "created_by", "last_edited_by", "archived"], actions: ["notion.pages.search"] },
      ],
      query_plans: [
        { integrationId: "notion", actionId: "notion.pages.search", query: {}, fields: ["title", "last_edited_time", "created_by"], max_results: 50 },
        { integrationId: "github", actionId: "github.pr.list", query: { q: "is:pr is:merged", sort: "updated", order: "desc", per_page: 50 }, fields: ["title", "merged_at", "author"], max_results: 50 },
      ],
      answer_contract: { entity_type: "NotionPage", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },
  {
    id: "ops-it-asset-register",
    name: "IT Asset Register",
    description: "Track IT assets and inventory from Airtable.",
    category: "Operations & Support",
    integrations: ["airtable"],
    trigger: "Prompt-based",
    output: "Table",
    prompt: "Show me the IT asset register with all tracked equipment.",
    spec: buildSpec({
      id: "ops-it-asset-register",
      name: "IT Asset Register",
      description: "IT asset and inventory management.",
      purpose: "Track and manage IT equipment and software licenses.",
      integrations: ["airtable"],
      entities: [makeAirtableRecordEntity(), makeAirtableBaseEntity()],
      actions: [makeAirtableRecordsListAction(), makeAirtableBasesListAction()],
      views: [
        { id: "assets-table", name: "Asset Register", type: "table", source: { entity: "AirtableRecord", statePath: "airtable.records" }, fields: ["id", "createdTime", "fields"], actions: ["airtable.records.list"] },
      ],
      query_plans: [{ integrationId: "airtable", actionId: "airtable.records.list", query: {}, fields: ["id", "createdTime", "fields"], max_results: 50 }],
      answer_contract: { entity_type: "AirtableRecord", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },
  {
    id: "ops-collab-health",
    name: "Collaboration Health Monitor",
    description: "Monitor collaboration health across Microsoft Teams and Slack channels.",
    category: "Operations & Support",
    integrations: ["microsoft_teams", "slack"],
    trigger: "Time-based",
    output: "Summary",
    prompt: "Show me collaboration health metrics across Teams and Slack.",
    spec: buildSpec({
      id: "ops-collab-health",
      name: "Collaboration Health Monitor",
      description: "Cross-platform collaboration monitoring.",
      purpose: "Ensure healthy communication patterns across teams.",
      integrations: ["microsoft_teams", "slack"],
      entities: [makeTeamsMessageEntity(), makeSlackChannelEntity()],
      actions: [makeTeamsMessagesListAction(), makeSlackChannelsListAction()],
      views: [
        { id: "collab-table", name: "Communication Activity", type: "table", source: { entity: "TeamsMessage", statePath: "teams.messages" }, fields: ["body", "from", "createdDateTime", "messageType", "importance", "webUrl"], actions: ["teams.messages.list"] },
        { id: "collab-dashboard", name: "Health Dashboard", type: "dashboard", source: { entity: "TeamsMessage", statePath: "teams.messages" }, fields: ["from", "createdDateTime", "messageType", "importance"], actions: [] },
      ],
      query_plans: [
        { integrationId: "microsoft_teams", actionId: "teams.messages.list", query: {}, fields: ["body", "from", "createdDateTime"], max_results: 50 },
        { integrationId: "slack", actionId: "slack.channels.list", query: {}, fields: ["name", "num_members", "topic"], max_results: 50 },
      ],
      answer_contract: { entity_type: "TeamsMessage", required_constraints: [], failure_policy: "empty_over_incorrect", list_shape: "array" },
    }),
  },
];
