export type OAuthProvider = {
  id: string;
  name: string;

  authUrl: string;
  tokenUrl: string;

  clientIdEnv: string;
  clientSecretEnv: string;

  scopes: string[];
  scopeSeparator?: " " | ",";

  supportsRefreshToken: boolean;

  extraAuthParams?: Record<string, string>;
};

export const OAUTH_PROVIDERS: Record<string, OAuthProvider> = {
  // --- Payments & Finance ---
  stripe: {
    id: "stripe",
    name: "Stripe",
    authUrl: "https://connect.stripe.com/oauth/authorize",
    tokenUrl: "https://connect.stripe.com/oauth/token",
    clientIdEnv: "STRIPE_CLIENT_ID",
    clientSecretEnv: "STRIPE_CLIENT_SECRET",
    scopes: ["read_write"],
    supportsRefreshToken: true,
  },
  paypal: {
    id: "paypal",
    name: "PayPal",
    authUrl: "https://www.paypal.com/signin/authorize",
    tokenUrl: "https://api-m.paypal.com/v1/oauth2/token",
    clientIdEnv: "PAYPAL_CLIENT_ID",
    clientSecretEnv: "PAYPAL_CLIENT_SECRET",
    scopes: ["openid", "profile", "email", "https://uri.paypal.com/services/invoicing"],
    supportsRefreshToken: true,
  },
  square: {
    id: "square",
    name: "Square",
    authUrl: "https://squareup.com/oauth2/authorize",
    tokenUrl: "https://connect.squareup.com/oauth2/token",
    clientIdEnv: "SQUARE_CLIENT_ID",
    clientSecretEnv: "SQUARE_CLIENT_SECRET",
    scopes: ["MERCHANT_PROFILE_READ", "PAYMENTS_READ", "CUSTOMERS_READ"],
    supportsRefreshToken: true,
  },
  paddle: {
    id: "paddle",
    name: "Paddle",
    authUrl: "https://login.paddle.com/oauth/authorize",
    tokenUrl: "https://login.paddle.com/oauth/token",
    clientIdEnv: "PADDLE_CLIENT_ID",
    clientSecretEnv: "PADDLE_CLIENT_SECRET",
    scopes: ["reports:read", "customers:read"],
    supportsRefreshToken: true,
  },
  chargebee: {
    id: "chargebee",
    name: "Chargebee",
    authUrl: "https://admin.chargebee.com/oauth/authorize",
    tokenUrl: "https://admin.chargebee.com/oauth/token",
    clientIdEnv: "CHARGEBEE_CLIENT_ID",
    clientSecretEnv: "CHARGEBEE_CLIENT_SECRET",
    scopes: ["read_only"],
    supportsRefreshToken: true,
  },

  // --- Analytics & Events ---
  ga4: {
    id: "ga4",
    name: "Google Analytics 4",
    authUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    clientIdEnv: "GOOGLE_CLIENT_ID",
    clientSecretEnv: "GOOGLE_CLIENT_SECRET",
    scopes: ["https://www.googleapis.com/auth/analytics.readonly"],
    supportsRefreshToken: true,
    extraAuthParams: { access_type: "offline", prompt: "consent" },
  },
  mixpanel: {
    id: "mixpanel",
    name: "Mixpanel",
    authUrl: "https://mixpanel.com/oauth/authorize", // Hypothetical/placeholder if API key only, but implementing per request
    tokenUrl: "https://mixpanel.com/oauth/access_token",
    clientIdEnv: "MIXPANEL_CLIENT_ID",
    clientSecretEnv: "MIXPANEL_CLIENT_SECRET",
    scopes: ["read"],
    supportsRefreshToken: true,
  },
  amplitude: {
    id: "amplitude",
    name: "Amplitude",
    authUrl: "https://amplitude.com/oauth/authorize", // Hypothetical
    tokenUrl: "https://amplitude.com/oauth/token",
    clientIdEnv: "AMPLITUDE_CLIENT_ID",
    clientSecretEnv: "AMPLITUDE_CLIENT_SECRET",
    scopes: ["read"],
    supportsRefreshToken: true,
  },
  segment: {
    id: "segment",
    name: "Segment",
    authUrl: "https://segment.com/oauth/authorize", // Hypothetical
    tokenUrl: "https://segment.com/oauth/token",
    clientIdEnv: "SEGMENT_CLIENT_ID",
    clientSecretEnv: "SEGMENT_CLIENT_SECRET",
    scopes: ["workspace:read"],
    supportsRefreshToken: true,
  },

  // --- CRM & Support ---
  hubspot: {
    id: "hubspot",
    name: "HubSpot",
    authUrl: "https://app.hubspot.com/oauth/authorize",
    tokenUrl: "https://api.hubapi.com/oauth/v1/token",
    clientIdEnv: "HUBSPOT_CLIENT_ID",
    clientSecretEnv: "HUBSPOT_CLIENT_SECRET",
    scopes: ["crm.objects.contacts.read", "crm.objects.companies.read", "crm.objects.deals.read"],
    supportsRefreshToken: true,
  },
  salesforce: {
    id: "salesforce",
    name: "Salesforce",
    authUrl: "https://login.salesforce.com/services/oauth2/authorize",
    tokenUrl: "https://login.salesforce.com/services/oauth2/token",
    clientIdEnv: "SALESFORCE_CLIENT_ID",
    clientSecretEnv: "SALESFORCE_CLIENT_SECRET",
    scopes: ["api", "refresh_token", "offline_access"],
    supportsRefreshToken: true,
  },
  zoho_crm: {
    id: "zoho_crm",
    name: "Zoho CRM",
    authUrl: "https://accounts.zoho.com/oauth/v2/auth",
    tokenUrl: "https://accounts.zoho.com/oauth/v2/token",
    clientIdEnv: "ZOHO_CLIENT_ID",
    clientSecretEnv: "ZOHO_CLIENT_SECRET",
    scopes: ["ZohoCRM.modules.ALL"],
    supportsRefreshToken: true,
    extraAuthParams: { access_type: "offline", prompt: "consent" },
  },
  pipedrive: {
    id: "pipedrive",
    name: "Pipedrive",
    authUrl: "https://oauth.pipedrive.com/oauth/authorize",
    tokenUrl: "https://oauth.pipedrive.com/oauth/token",
    clientIdEnv: "PIPEDRIVE_CLIENT_ID",
    clientSecretEnv: "PIPEDRIVE_CLIENT_SECRET",
    scopes: ["deals:read", "contacts:read"],
    supportsRefreshToken: true,
  },
  intercom: {
    id: "intercom",
    name: "Intercom",
    authUrl: "https://app.intercom.com/oauth",
    tokenUrl: "https://api.intercom.io/auth/eagle/token",
    clientIdEnv: "INTERCOM_CLIENT_ID",
    clientSecretEnv: "INTERCOM_CLIENT_SECRET",
    scopes: [],
    supportsRefreshToken: false, // Intercom uses long-lived tokens usually, but standard oauth flow exists
  },
  zendesk: {
    id: "zendesk",
    name: "Zendesk",
    authUrl: "https://global.zendesk.com/oauth/authorizations/new",
    tokenUrl: "https://global.zendesk.com/oauth/tokens",
    clientIdEnv: "ZENDESK_CLIENT_ID",
    clientSecretEnv: "ZENDESK_CLIENT_SECRET",
    scopes: ["read"],
    supportsRefreshToken: true,
  },
  freshdesk: {
    id: "freshdesk",
    name: "Freshdesk",
    authUrl: "https://freshdesk.com/oauth/authorize", // Hypothetical
    tokenUrl: "https://freshdesk.com/oauth/token",
    clientIdEnv: "FRESHDESK_CLIENT_ID",
    clientSecretEnv: "FRESHDESK_CLIENT_SECRET",
    scopes: ["read"],
    supportsRefreshToken: true,
  },

  // --- Marketing & Growth ---
  google_ads: {
    id: "google_ads",
    name: "Google Ads",
    authUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    clientIdEnv: "GOOGLE_CLIENT_ID",
    clientSecretEnv: "GOOGLE_CLIENT_SECRET",
    scopes: ["https://www.googleapis.com/auth/adwords"],
    supportsRefreshToken: true,
    extraAuthParams: { access_type: "offline", prompt: "consent" },
  },
  meta_ads: {
    id: "meta_ads",
    name: "Meta Ads",
    authUrl: "https://www.facebook.com/v18.0/dialog/oauth",
    tokenUrl: "https://graph.facebook.com/v18.0/oauth/access_token",
    clientIdEnv: "META_CLIENT_ID",
    clientSecretEnv: "META_CLIENT_SECRET",
    scopes: ["ads_read", "ads_management"],
    supportsRefreshToken: true, // Long-lived tokens exchange
  },
  linkedin_ads: {
    id: "linkedin_ads",
    name: "LinkedIn Ads",
    authUrl: "https://www.linkedin.com/oauth/v2/authorization",
    tokenUrl: "https://www.linkedin.com/oauth/v2/accessToken",
    clientIdEnv: "LINKEDIN_CLIENT_ID",
    clientSecretEnv: "LINKEDIN_CLIENT_SECRET",
    scopes: ["r_ads", "r_ads_reporting"],
    supportsRefreshToken: true,
  },
  tiktok_ads: {
    id: "tiktok_ads",
    name: "TikTok Ads",
    authUrl: "https://ads.tiktok.com/marketing_api/auth",
    tokenUrl: "https://ads.tiktok.com/open_api/v1.3/oauth2/access_token/",
    clientIdEnv: "TIKTOK_CLIENT_ID",
    clientSecretEnv: "TIKTOK_CLIENT_SECRET",
    scopes: ["ads.read"],
    supportsRefreshToken: true,
  },
  mailchimp: {
    id: "mailchimp",
    name: "Mailchimp",
    authUrl: "https://login.mailchimp.com/oauth2/authorize",
    tokenUrl: "https://login.mailchimp.com/oauth2/token",
    clientIdEnv: "MAILCHIMP_CLIENT_ID",
    clientSecretEnv: "MAILCHIMP_CLIENT_SECRET",
    scopes: [],
    supportsRefreshToken: false, // Mailchimp uses metadata ping to find DC
  },
  klaviyo: {
    id: "klaviyo",
    name: "Klaviyo",
    authUrl: "https://www.klaviyo.com/oauth/authorize", // Hypothetical (Klaviyo is mostly API key but adding as requested)
    tokenUrl: "https://www.klaviyo.com/oauth/token",
    clientIdEnv: "KLAVIYO_CLIENT_ID",
    clientSecretEnv: "KLAVIYO_CLIENT_SECRET",
    scopes: ["campaigns:read", "metrics:read"],
    supportsRefreshToken: true,
  },
  customer_io: {
    id: "customer_io",
    name: "Customer.io",
    authUrl: "https://fly.customer.io/oauth/authorize", // Hypothetical
    tokenUrl: "https://fly.customer.io/oauth/token",
    clientIdEnv: "CUSTOMERIO_CLIENT_ID",
    clientSecretEnv: "CUSTOMERIO_CLIENT_SECRET",
    scopes: ["read"],
    supportsRefreshToken: true,
  },

  // --- Developer & Engineering ---
  github: {
    id: "github",
    name: "GitHub",
    authUrl: "https://github.com/login/oauth/authorize",
    tokenUrl: "https://github.com/login/oauth/access_token",
    clientIdEnv: "GITHUB_CLIENT_ID",
    clientSecretEnv: "GITHUB_CLIENT_SECRET",
    scopes: ["repo", "user"],
    supportsRefreshToken: false, // GitHub tokens are persistent
  },
  gitlab: {
    id: "gitlab",
    name: "GitLab",
    authUrl: "https://gitlab.com/oauth/authorize",
    tokenUrl: "https://gitlab.com/oauth/token",
    clientIdEnv: "GITLAB_CLIENT_ID",
    clientSecretEnv: "GITLAB_CLIENT_SECRET",
    scopes: ["api"],
    supportsRefreshToken: true,
  },
  bitbucket: {
    id: "bitbucket",
    name: "Bitbucket",
    authUrl: "https://bitbucket.org/site/oauth2/authorize",
    tokenUrl: "https://bitbucket.org/site/oauth2/access_token",
    clientIdEnv: "BITBUCKET_CLIENT_ID",
    clientSecretEnv: "BITBUCKET_CLIENT_SECRET",
    scopes: ["repository", "account"],
    supportsRefreshToken: true,
  },
  jira: {
    id: "jira",
    name: "Jira",
    authUrl: "https://auth.atlassian.com/authorize",
    tokenUrl: "https://auth.atlassian.com/oauth/token",
    clientIdEnv: "ATLASSIAN_CLIENT_ID",
    clientSecretEnv: "ATLASSIAN_CLIENT_SECRET",
    scopes: ["read:jira-work", "offline_access"],
    supportsRefreshToken: true,
    extraAuthParams: { audience: "api.atlassian.com", prompt: "consent" },
  },
  linear: {
    id: "linear",
    name: "Linear",
    authUrl: "https://linear.app/oauth/authorize",
    tokenUrl: "https://api.linear.app/oauth/token",
    clientIdEnv: "LINEAR_CLIENT_ID",
    clientSecretEnv: "LINEAR_CLIENT_SECRET",
    scopes: ["read"],
    supportsRefreshToken: false,
  },
  asana: {
    id: "asana",
    name: "Asana",
    authUrl: "https://app.asana.com/-/oauth_authorize",
    tokenUrl: "https://app.asana.com/-/oauth_token",
    clientIdEnv: "ASANA_CLIENT_ID",
    clientSecretEnv: "ASANA_CLIENT_SECRET",
    scopes: ["default"],
    supportsRefreshToken: true,
  },
  clickup: {
    id: "clickup",
    name: "ClickUp",
    authUrl: "https://app.clickup.com/api",
    tokenUrl: "https://api.clickup.com/api/v2/oauth/token",
    clientIdEnv: "CLICKUP_CLIENT_ID",
    clientSecretEnv: "CLICKUP_CLIENT_SECRET",
    scopes: [],
    supportsRefreshToken: false,
  },
  sentry: {
    id: "sentry",
    name: "Sentry",
    authUrl: "https://sentry.io/oauth/authorize/",
    tokenUrl: "https://sentry.io/oauth/token/",
    clientIdEnv: "SENTRY_CLIENT_ID",
    clientSecretEnv: "SENTRY_CLIENT_SECRET",
    scopes: ["project:read", "event:read", "org:read"],
    supportsRefreshToken: true,
  },
  datadog: {
    id: "datadog",
    name: "Datadog",
    authUrl: "https://app.datadoghq.com/oauth2/v1/authorize",
    tokenUrl: "https://app.datadoghq.com/oauth2/v1/token",
    clientIdEnv: "DATADOG_CLIENT_ID",
    clientSecretEnv: "DATADOG_CLIENT_SECRET",
    scopes: [],
    supportsRefreshToken: true,
  },
  new_relic: {
    id: "new_relic",
    name: "New Relic",
    authUrl: "https://oauth.newrelic.com/login", // Hypothetical
    tokenUrl: "https://oauth.newrelic.com/token",
    clientIdEnv: "NEWRELIC_CLIENT_ID",
    clientSecretEnv: "NEWRELIC_CLIENT_SECRET",
    scopes: [],
    supportsRefreshToken: true,
  },

  // --- Cloud & Infra ---
  aws: {
    id: "aws",
    name: "AWS",
    authUrl: "https://signin.aws.amazon.com/oauth", // Hypothetical (AWS usually uses IAM keys)
    tokenUrl: "https://signin.aws.amazon.com/token",
    clientIdEnv: "AWS_CLIENT_ID",
    clientSecretEnv: "AWS_CLIENT_SECRET",
    scopes: [],
    supportsRefreshToken: true,
  },
  gcp: {
    id: "gcp",
    name: "GCP",
    authUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    clientIdEnv: "GOOGLE_CLIENT_ID",
    clientSecretEnv: "GOOGLE_CLIENT_SECRET",
    scopes: ["https://www.googleapis.com/auth/cloud-platform.read-only"],
    supportsRefreshToken: true,
    extraAuthParams: { access_type: "offline", prompt: "consent" },
  },
  azure: {
    id: "azure",
    name: "Azure",
    authUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
    tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
    clientIdEnv: "AZURE_CLIENT_ID",
    clientSecretEnv: "AZURE_CLIENT_SECRET",
    scopes: ["https://management.azure.com/.default", "offline_access"],
    supportsRefreshToken: true,
  },
  vercel: {
    id: "vercel",
    name: "Vercel",
    authUrl: "https://vercel.com/oauth/authorize",
    tokenUrl: "https://api.vercel.com/v2/oauth/access_token",
    clientIdEnv: "VERCEL_CLIENT_ID",
    clientSecretEnv: "VERCEL_CLIENT_SECRET",
    scopes: [],
    supportsRefreshToken: false,
  },
  netlify: {
    id: "netlify",
    name: "Netlify",
    authUrl: "https://app.netlify.com/authorize",
    tokenUrl: "https://api.netlify.com/oauth/token",
    clientIdEnv: "NETLIFY_CLIENT_ID",
    clientSecretEnv: "NETLIFY_CLIENT_SECRET",
    scopes: [],
    supportsRefreshToken: true,
  },
  render: {
    id: "render",
    name: "Render",
    authUrl: "https://api.render.com/oauth/authorize", // Hypothetical
    tokenUrl: "https://api.render.com/oauth/token",
    clientIdEnv: "RENDER_CLIENT_ID",
    clientSecretEnv: "RENDER_CLIENT_SECRET",
    scopes: ["read"],
    supportsRefreshToken: true,
  },

  // --- Files & Knowledge ---
  google_drive: {
    id: "google_drive",
    name: "Google Drive",
    authUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    clientIdEnv: "GOOGLE_CLIENT_ID",
    clientSecretEnv: "GOOGLE_CLIENT_SECRET",
    scopes: ["https://www.googleapis.com/auth/drive.readonly"],
    supportsRefreshToken: true,
    extraAuthParams: { access_type: "offline", prompt: "consent" },
  },
  google_sheets: {
    id: "google_sheets",
    name: "Google Sheets",
    authUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    clientIdEnv: "GOOGLE_CLIENT_ID",
    clientSecretEnv: "GOOGLE_CLIENT_SECRET",
    scopes: ["https://www.googleapis.com/auth/spreadsheets.readonly"],
    supportsRefreshToken: true,
    extraAuthParams: { access_type: "offline", prompt: "consent" },
  },
  airtable: {
    id: "airtable",
    name: "Airtable",
    authUrl: "https://airtable.com/oauth2/v1/authorize",
    tokenUrl: "https://airtable.com/oauth2/v1/token",
    clientIdEnv: "AIRTABLE_CLIENT_ID",
    clientSecretEnv: "AIRTABLE_CLIENT_SECRET",
    scopes: ["data.records:read", "schema.bases:read"],
    supportsRefreshToken: true,
    extraAuthParams: { code_challenge_method: "S256" }, // PKCE often required
  },
  notion: {
    id: "notion",
    name: "Notion",
    authUrl: "https://api.notion.com/v1/oauth/authorize",
    tokenUrl: "https://api.notion.com/v1/oauth/token",
    clientIdEnv: "NOTION_CLIENT_ID",
    clientSecretEnv: "NOTION_CLIENT_SECRET",
    scopes: [],
    supportsRefreshToken: false,
  },
  confluence: {
    id: "confluence",
    name: "Confluence",
    authUrl: "https://auth.atlassian.com/authorize",
    tokenUrl: "https://auth.atlassian.com/oauth/token",
    clientIdEnv: "ATLASSIAN_CLIENT_ID",
    clientSecretEnv: "ATLASSIAN_CLIENT_SECRET",
    scopes: ["read:confluence-content.all", "offline_access"],
    supportsRefreshToken: true,
    extraAuthParams: { audience: "api.atlassian.com", prompt: "consent" },
  },
  dropbox: {
    id: "dropbox",
    name: "Dropbox",
    authUrl: "https://www.dropbox.com/oauth2/authorize",
    tokenUrl: "https://api.dropbox.com/oauth2/token",
    clientIdEnv: "DROPBOX_CLIENT_ID",
    clientSecretEnv: "DROPBOX_CLIENT_SECRET",
    scopes: ["files.content.read", "sharing.read"],
    supportsRefreshToken: true,
    extraAuthParams: { token_access_type: "offline" },
  },
  box: {
    id: "box",
    name: "Box",
    authUrl: "https://account.box.com/api/oauth2/authorize",
    tokenUrl: "https://api.box.com/oauth2/token",
    clientIdEnv: "BOX_CLIENT_ID",
    clientSecretEnv: "BOX_CLIENT_SECRET",
    scopes: [],
    supportsRefreshToken: true,
  },

  // --- Identity & HR ---
  okta: {
    id: "okta",
    name: "Okta",
    authUrl: "https://{yourOktaDomain}/oauth2/v1/authorize", // Requires domain injection
    tokenUrl: "https://{yourOktaDomain}/oauth2/v1/token",
    clientIdEnv: "OKTA_CLIENT_ID",
    clientSecretEnv: "OKTA_CLIENT_SECRET",
    scopes: ["openid", "profile", "email"],
    supportsRefreshToken: true,
  },
  azure_ad: {
    id: "azure_ad",
    name: "Azure AD",
    authUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
    tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
    clientIdEnv: "AZURE_CLIENT_ID",
    clientSecretEnv: "AZURE_CLIENT_SECRET",
    scopes: ["User.Read", "Directory.Read.All", "offline_access"],
    supportsRefreshToken: true,
  },
  google_workspace: {
    id: "google_workspace",
    name: "Google Workspace",
    authUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    clientIdEnv: "GOOGLE_CLIENT_ID",
    clientSecretEnv: "GOOGLE_CLIENT_SECRET",
    scopes: ["https://www.googleapis.com/auth/admin.directory.user.readonly"],
    supportsRefreshToken: true,
    extraAuthParams: { access_type: "offline", prompt: "consent" },
  },
  rippling: {
    id: "rippling",
    name: "Rippling",
    authUrl: "https://app.rippling.com/oauth/authorize", // Hypothetical
    tokenUrl: "https://app.rippling.com/oauth/token",
    clientIdEnv: "RIPPLING_CLIENT_ID",
    clientSecretEnv: "RIPPLING_CLIENT_SECRET",
    scopes: [],
    supportsRefreshToken: true,
  },
  bamboohr: {
    id: "bamboohr",
    name: "BambooHR",
    authUrl: "https://api.bamboohr.com/oauth/authorize", // Hypothetical
    tokenUrl: "https://api.bamboohr.com/oauth/token",
    clientIdEnv: "BAMBOOHR_CLIENT_ID",
    clientSecretEnv: "BAMBOOHR_CLIENT_SECRET",
    scopes: [],
    supportsRefreshToken: false, // Basic auth common
  },
  deel: {
    id: "deel",
    name: "Deel",
    authUrl: "https://app.deel.com/oauth2/authorize",
    tokenUrl: "https://api.deel.com/oauth2/token",
    clientIdEnv: "DEEL_CLIENT_ID",
    clientSecretEnv: "DEEL_CLIENT_SECRET",
    scopes: ["contracts:read", "people:read"],
    supportsRefreshToken: true,
  },
  workday: {
    id: "workday",
    name: "Workday",
    authUrl: "https://impl.workday.com/oauth2/authorize", // Hypothetical
    tokenUrl: "https://impl.workday.com/oauth2/token",
    clientIdEnv: "WORKDAY_CLIENT_ID",
    clientSecretEnv: "WORKDAY_CLIENT_SECRET",
    scopes: [],
    supportsRefreshToken: true,
  },

  // --- Messaging & Actions ---
  slack: {
    id: "slack",
    name: "Slack",
    authUrl: "https://slack.com/oauth/v2/authorize",
    tokenUrl: "https://slack.com/api/oauth.v2.access",
    clientIdEnv: "SLACK_CLIENT_ID",
    clientSecretEnv: "SLACK_CLIENT_SECRET",
    scopes: ["channels:read", "chat:write", "files:read"],
    supportsRefreshToken: false, // Slack uses persistent tokens mostly
  },
  teams: {
    id: "teams",
    name: "Microsoft Teams",
    authUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
    tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
    clientIdEnv: "AZURE_CLIENT_ID",
    clientSecretEnv: "AZURE_CLIENT_SECRET",
    scopes: ["Channel.ReadBasic.All", "ChatMessage.Read.All", "offline_access"],
    supportsRefreshToken: true,
  },
  discord: {
    id: "discord",
    name: "Discord",
    authUrl: "https://discord.com/api/oauth2/authorize",
    tokenUrl: "https://discord.com/api/oauth2/token",
    clientIdEnv: "DISCORD_CLIENT_ID",
    clientSecretEnv: "DISCORD_CLIENT_SECRET",
    scopes: ["identify", "guilds"],
    supportsRefreshToken: true,
  },
  pagerduty: {
    id: "pagerduty",
    name: "PagerDuty",
    authUrl: "https://app.pagerduty.com/oauth/authorize",
    tokenUrl: "https://app.pagerduty.com/oauth/token",
    clientIdEnv: "PAGERDUTY_CLIENT_ID",
    clientSecretEnv: "PAGERDUTY_CLIENT_SECRET",
    scopes: ["read"],
    supportsRefreshToken: false,
  },

  whatsapp: {
    id: "whatsapp",
    name: "WhatsApp",
    authUrl: "https://www.facebook.com/v18.0/dialog/oauth", // Via Meta
    tokenUrl: "https://graph.facebook.com/v18.0/oauth/access_token",
    clientIdEnv: "META_CLIENT_ID",
    clientSecretEnv: "META_CLIENT_SECRET",
    scopes: ["whatsapp_business_messaging", "whatsapp_business_management"],
    supportsRefreshToken: true,
  },

  // --- AI Providers ---
  azure_openai: {
    id: "azure_openai",
    name: "Azure OpenAI",
    authUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
    tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
    clientIdEnv: "AZURE_CLIENT_ID",
    clientSecretEnv: "AZURE_CLIENT_SECRET",
    scopes: ["https://cognitiveservices.azure.com/.default", "offline_access"],
    supportsRefreshToken: true,
  },

  huggingface: {
    id: "huggingface",
    name: "HuggingFace",
    authUrl: "https://huggingface.co/oauth/authorize",
    tokenUrl: "https://huggingface.co/oauth/token",
    clientIdEnv: "HUGGINGFACE_CLIENT_ID",
    clientSecretEnv: "HUGGINGFACE_CLIENT_SECRET",
    scopes: ["inference-api"],
    supportsRefreshToken: true,
  },
};
